baseURL = 'https://ta180m.exozy.me/'
languageCode = 'en-us'
title = 'Some Random Website'
theme = 'gokarna'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    pre = '<span data-feather="aperture"></span>'
    weight = 1
  [[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    pre = '<span data-feather="package"></span>'
    weight = 2
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    pre = '<span data-feather="tag"></span>'
    weight = 3
  [[menu.main]]
    identifier = 'feed'
    name = 'Feed'
    url = '/index.xml'
    pre = '<span data-feather="rss"></span>'
    weight = 4
  [[menu.main]]
    identifier = 'git'
    name = 'Git'
    url = 'https://git.exozy.me/Ta180m/website'
    pre = '<span data-feather="git-pull-request"></span>'
    weight = 5

[params]
  avatarURL = '/dodecahedra/logo.webp'
  avatarSize = 'size-xl'
  description = '(+ (Element 73) (Ï„/2 radians to degrees) (SI unit for length))'
  accentColor = '#00dd42'
  footer = 'ðŸŽ‰ Made with Hugo and frustration! - CC BY-SA 4.0'
  socialIcons = [
      {name = 'protonmail', url = '/about/email'},
      {name = 'matrix', url = 'https://matrix.to/#/@ta180m:exozy.me'},
      {name = 'mastodon', url = 'https://social.exozy.me/@ta180m'},
      {name = 'peertube', url = 'https://tube.exozy.me/a/ta180m/video-channels'},
      {name = 'gitea', url = 'https://git.exozy.me/Ta180m/'},
      {name = 'github', url = 'https://github.com/Ta180m/'},
      {name = 'codeforces', url = 'https://codeforces.com/profile/Ta180m'},
      {name = 'archlinux', url = 'https://aur.archlinux.org/packages/?K=Ta180m&SeB=m'},
      {name = 'liberapay', url = 'https://liberapay.com/Ta180m/'},
    ]
